# Generated by Django 4.2.7 on 2026-03-03 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='排放源名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='编码')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '排放源',
                'verbose_name_plural': '排放源',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='地区名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='地区编码')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='emissions.region', verbose_name='上级地区')),
            ],
            options={
                'verbose_name': '地区',
                'verbose_name_plural': '地区',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='行业名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='行业编码')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industries', to='emissions.emissionsource', verbose_name='所属排放源')),
            ],
            options={
                'verbose_name': '行业',
                'verbose_name_plural': '行业',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('quarter', models.IntegerField(choices=[(1, '第一季度'), (2, '第二季度'), (3, '第三季度'), (4, '第四季度')], verbose_name='季度')),
                ('emission_amount', models.FloatField(verbose_name='排放量(万吨CO2)')),
                ('energy_consumption', models.FloatField(default=0, verbose_name='能源消耗(万吨标准煤)')),
                ('gdp', models.FloatField(default=0, verbose_name='GDP(亿元)')),
                ('population', models.FloatField(default=0, verbose_name='人口(万人)')),
                ('energy_efficiency', models.FloatField(default=0, verbose_name='能源效率(吨CO2/万元GDP)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='emissions.industry', verbose_name='行业')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='emissions.region', verbose_name='地区')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='emissions.emissionsource', verbose_name='排放源')),
            ],
            options={
                'verbose_name': '排放记录',
                'verbose_name_plural': '排放记录',
                'ordering': ['-year', '-quarter'],
                'indexes': [models.Index(fields=['year', 'quarter'], name='emissions_e_year_5c2f6a_idx'), models.Index(fields=['region', 'year'], name='emissions_e_region__a192fd_idx'), models.Index(fields=['industry', 'year'], name='emissions_e_industr_31c4ed_idx'), models.Index(fields=['source', 'year'], name='emissions_e_source__317ea5_idx')],
            },
        ),
    ]
