# Generated by Django 4.2.7 on 2026-03-03 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThresholdConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('method', models.CharField(choices=[('normal', '正态分布法'), ('standard', '参考排放标准')], max_length=20, verbose_name='阈值方法')),
                ('mean_value', models.FloatField(blank=True, null=True, verbose_name='均值(μ)')),
                ('std_value', models.FloatField(blank=True, null=True, verbose_name='标准差(σ)')),
                ('upper_limit', models.FloatField(verbose_name='预警上限(万吨CO2)')),
                ('warning_level', models.CharField(choices=[('yellow', '黄色预警'), ('orange', '橙色预警'), ('red', '红色预警')], default='yellow', max_length=10, verbose_name='预警级别')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emissions.industry', verbose_name='行业')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emissions.region', verbose_name='地区')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emissions.emissionsource', verbose_name='排放源')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '阈值配置',
                'verbose_name_plural': '阈值配置',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_level', models.CharField(choices=[('yellow', '黄色预警'), ('orange', '橙色预警'), ('red', '红色预警')], max_length=10, verbose_name='预警级别')),
                ('alert_message', models.TextField(verbose_name='预警信息')),
                ('emission_value', models.FloatField(verbose_name='排放值(万吨CO2)')),
                ('threshold_value', models.FloatField(verbose_name='阈值(万吨CO2)')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('emission_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='emissions.emissionrecord', verbose_name='排放记录')),
                ('threshold', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alerts.thresholdconfig', verbose_name='触发阈值')),
            ],
            options={
                'verbose_name': '预警记录',
                'verbose_name_plural': '预警记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
